name: Atualizar estatísticas

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Gerar estatísticas
        run: |
          mkdir -p assets
          node generate-stats.js

      - name: Salvar estatísticas
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/github-stats.svg
          git diff --cached --quiet || git commit -m "Atualiza estatísticas"
          git push
